baseURL: "https://gjeusel.github.io/artcode/"
languageCode: "en-us"
title: "ArtCode"
#theme: "er"

publishDir: "docs"

MetaDataFormat: "yaml"
DefaultContentLanguage: "en"
SectionPagesMenu: "main"
Paginate: 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics: ""
enableRobotsTXT: true

pygmentsStyle: "tango"


#staticman:
    #api: https://api.staticman.net/v2/entry/<USERNAME>/<REPOSITORY-BLOGNAME>/master/comments
    #pulls: https://github.com/<USERNAME>/<REPOSITORY-BLOGNAME>/pulls
    #recaptcha:
    #    sitekey: "6LeGeTgUAAAAAAqVrfTwox1kJQFdWl-mLzKasV0v"
    #    secret: "hsGjWtWHR4HK4pT7cUsWTArJdZDxxE2pkdg/ArwCguqYQrhuubjj3RS9C5qa8xu4cx/Y9EwHwAMEeXPCZbLR9eW1K9L

params:
    favicon: "img/logo.jpg"
    description: "Bring knowledge."

    # Structure / Tools:
    #math: true  # load katex
    #showtoc: false  # show table of content
    showTagCloud: true  # show tag cloud

    # Social:
    facebook: ""
    twitter: ""
    instagram: ""
    youtube: ""
    github: "gjeusel"
    linkedin: "guillaume-jeusel"

    # Style:
    coverImageHome: "http://www.wallpast.com/wp-content/uploads/2017/12/samurai-champloo-wallpaper-samurai-champloo-wallpaper-samurai-champloo-wallpaper-phone-samurai-champloo-swords-wallpaper-samurai-champloo.jpg"
    #customcss: ["css/custom.css",]
    #customjs: ["js/custom.js", ]

    intro:
        pic:
            src: "https://media.licdn.com/dms/image/C5603AQEheknaCVbxcw/profile-displayphoto-shrink_200_200/0?e=1538611200&v=beta&t=fzGvKFnz440Fcux3-dg7-BJR2Wfy2SbAgzlcib5TT9I"
            circle: false
            hexagone: true

        header: "artcode"
        paragraph: "Just playing around with Hugo. And it's awesome"

menu:
    main:
        - identifier: "cheatsheets"
          name: "Cheatsheets"
          url: "/cheatsheets/"
          weight: 1

        - identifier: "posts"
          name: "Posts"
          url: "/posts/"
          weight: 1

        - name: "About"
          identifier: "about"
          url: "/about/"
          weight: 3
